# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-13 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('telephone', models.CharField(max_length=16, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('userface', models.CharField(max_length=255, null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='class_attribute',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('attribute_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='class_method',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='class_table',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attribute_num', models.IntegerField(null=True)),
                ('method_num', models.IntegerField(null=True)),
                ('for_num', models.IntegerField(null=True)),
                ('switch_num', models.IntegerField(null=True)),
                ('if_num', models.IntegerField(null=True)),
                ('while_num', models.IntegerField(null=True)),
                ('do_while_num', models.IntegerField(null=True)),
                ('express_state_num', models.IntegerField(null=True)),
                ('var_sate_num', models.IntegerField(null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='detect_feedback',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('mild_sim', models.FloatField(null=True)),
                ('moderate_sim', models.FloatField(null=True)),
                ('severe_sim', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detect_record',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, null=True)),
                ('degree', models.CharField(default='SIMPLE', max_length=255)),
                ('func_type', models.CharField(default='PROJECT', max_length=255)),
                ('remake', models.CharField(max_length=255, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('detect_time', models.IntegerField(null=True)),
                ('file_num', models.IntegerField(null=True)),
                ('exception_file_num', models.IntegerField(null=True)),
                ('normal_file_num', models.IntegerField(null=True)),
                ('mild_file_num', models.IntegerField(null=True)),
                ('moderate_file_num', models.IntegerField(null=True)),
                ('severe_file_num', models.IntegerField(null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('type', models.CharField(max_length=128, null=True)),
                ('encoding', models.CharField(max_length=128, null=True)),
                ('copy_rank', models.IntegerField(default=0)),
                ('is_normal', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='file_class',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.class_table')),
                ('file_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.file')),
            ],
        ),
        migrations.CreateModel(
            name='file_group',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('file_num', models.IntegerField(null=True)),
                ('exception_file_num', models.IntegerField(null=True)),
                ('normal_file_num', models.IntegerField(null=True)),
                ('mild_file_num', models.IntegerField(null=True)),
                ('moderate_file_num', models.IntegerField(null=True)),
                ('severe_file_num', models.IntegerField(null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='file_group_file',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('file_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.file')),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.file_group')),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('text1_start_line', models.IntegerField(null=True)),
                ('text1_start_pos', models.IntegerField(null=True)),
                ('text1_end_line', models.IntegerField(null=True)),
                ('text1_end_pos', models.IntegerField(null=True)),
                ('text2_start_line', models.IntegerField(null=True)),
                ('text2_start_pos', models.IntegerField(null=True)),
                ('text2_end_line', models.IntegerField(null=True)),
                ('text2_end_pos', models.IntegerField(null=True)),
                ('len', models.IntegerField(null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=64, null=True)),
                ('path', models.CharField(max_length=64, null=True)),
                ('component', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('iconCls', models.CharField(max_length=64, null=True)),
                ('keepAlive', models.BooleanField(default=True)),
                ('requireAuth', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.menu')),
            ],
        ),
        migrations.CreateModel(
            name='menu_role',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodePass.menu')),
            ],
        ),
        migrations.CreateModel(
            name='method',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('return_type', models.CharField(max_length=255, null=True)),
                ('param_list', models.CharField(max_length=255, null=True)),
                ('var_sate', models.TextField(null=True)),
                ('for_num', models.IntegerField(null=True)),
                ('switch_num', models.IntegerField(null=True)),
                ('if_num', models.IntegerField(null=True)),
                ('while_num', models.IntegerField(null=True)),
                ('do_while_num', models.IntegerField(null=True)),
                ('express_state_num', models.IntegerField(null=True)),
                ('var_sate_num', models.IntegerField(null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='msgcontent',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, null=True)),
                ('message', models.CharField(max_length=64, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='oplog',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('operate', models.CharField(max_length=255, null=True)),
                ('adminid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.admin')),
            ],
        ),
        migrations.CreateModel(
            name='record_group',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.file_group')),
                ('record_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.detect_record')),
            ],
        ),
        migrations.CreateModel(
            name='record_user',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.admin')),
                ('record_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.detect_record')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True)),
                ('nameZh', models.CharField(max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='similarity',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('attribute_similarity', models.FloatField(null=True)),
                ('struct_similarity', models.FloatField(null=True)),
                ('sample_text_similarity', models.FloatField(null=True)),
                ('text_similarity', models.FloatField(null=True)),
                ('similarity', models.FloatField(null=True)),
                ('is_max_similarity', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('file1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file1_foreign', to='CodePass.file')),
                ('file2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file2_foreign', to='CodePass.file')),
            ],
        ),
        migrations.CreateModel(
            name='similarity_matches',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.matches')),
                ('similarity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.similarity')),
            ],
        ),
        migrations.CreateModel(
            name='sysmsg',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('type', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=False)),
                ('adminid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.admin')),
                ('mid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.msgcontent')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('telephone', models.CharField(max_length=16, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('disabled', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('userface', models.CharField(max_length=255, null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=50, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.user')),
            ],
            managers=[
                ('object1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='user_role',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodePass.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodePass.user')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.user'),
        ),
        migrations.AddField(
            model_name='record_user',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.user'),
        ),
        migrations.AddField(
            model_name='menu_role',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodePass.role'),
        ),
        migrations.AddField(
            model_name='detect_record',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.file'),
        ),
        migrations.AddField(
            model_name='detect_feedback',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodePass.detect_record'),
        ),
        migrations.AddField(
            model_name='class_method',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.class_table'),
        ),
        migrations.AddField(
            model_name='class_method',
            name='method_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.method'),
        ),
        migrations.AddField(
            model_name='class_attribute',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodePass.class_table'),
        ),
    ]
