# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-06-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodePass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detect_feedback',
            name='mild_sim',
        ),
        migrations.RemoveField(
            model_name='detect_feedback',
            name='moderate_sim',
        ),
        migrations.RemoveField(
            model_name='detect_feedback',
            name='record',
        ),
        migrations.RemoveField(
            model_name='detect_feedback',
            name='severe_sim',
        ),
        migrations.AddField(
            model_name='detect_feedback',
            name='attribute_similarity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detect_feedback',
            name='copy_rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detect_feedback',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CodePass.file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detect_feedback',
            name='struct_similarity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detect_feedback',
            name='text_similarity',
            field=models.FloatField(default=0, null=True),
        ),
    ]
